# Generated by Django 3.2.9 on 2022-04-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_name', models.CharField(max_length=200)),
                ('compliance_score', models.IntegerField(default=0)),
                ('compliance_start_date', models.DateTimeField(null=True)),
                ('compliance_end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=500)),
                ('check_description', models.CharField(blank=True, max_length=700)),
                ('check_status', models.BooleanField(default=False)),
                ('check_evidence_document', models.CharField(blank=True, max_length=200000, null=True)),
                ('doc_ref', models.CharField(blank=True, default='8CFHBCH7TO', max_length=200, null=True)),
                ('check_evidence', models.CharField(blank=True, max_length=700, null=True)),
                ('parent_compliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliance_management.compliancedetail')),
            ],
        ),
    ]
