# Generated by Django 3.2.9 on 2022-09-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_alter_folderdocument_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderdocument',
            name='doc_ref',
            field=models.CharField(blank=True, default='5SW0YXIN8Q', max_length=200, null=True),
        ),
    ]
