# Generated by Django 3.2.9 on 2022-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0016_alter_folderdocument_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderdocument',
            name='doc_ref',
            field=models.CharField(blank=True, default='NLF59YERKI', max_length=200, null=True),
        ),
    ]
