# Generated by Django 3.2.9 on 2022-05-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='doc_ref',
            field=models.CharField(blank=True, default='S2EO7O1JK0', max_length=200, null=True),
        ),
    ]
