# Generated by Django 3.2.9 on 2022-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_manager', '0002_alter_contractdetail_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='doc_ref',
            field=models.CharField(blank=True, default='C2L77EUXY0', max_length=200, null=True),
        ),
    ]
