# Generated by Django 3.2.9 on 2022-09-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_manager', '0012_alter_contractdetail_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='doc_ref',
            field=models.CharField(blank=True, default='RU18GB1ZOG', max_length=200, null=True),
        ),
    ]
