# Generated by Django 3.2.9 on 2023-01-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_manager', '0020_alter_contractdetail_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='doc_ref',
            field=models.CharField(blank=True, default='RLNZQV9LCB', max_length=200, null=True),
        ),
    ]
