# Generated by Django 3.2.9 on 2022-09-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profile_photo_user_prof_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
