# Generated by Django 3.2.9 on 2022-09-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_prof_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prof_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
