# Generated by Django 3.2.9 on 2022-04-05 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(default=False, verbose_name='description')),
                ('vote_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('vote_end_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('supporting_documents', models.CharField(blank=True, max_length=200000, null=True)),
                ('doc_ref', models.CharField(blank=True, default='U5QJTVP2JO', max_length=200, null=True)),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('abstain_votes', models.IntegerField(default=0)),
                ('yes_percentage', models.IntegerField(default=0)),
                ('no_percentage', models.IntegerField(default=0)),
                ('abstain_percentage', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voteqn_created_by', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='voters_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votingquestion')),
            ],
        ),
    ]
