# Generated by Django 3.2.9 on 2022-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_alter_votingquestion_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingquestion',
            name='doc_ref',
            field=models.CharField(blank=True, default='5X4JZ0K5N9', max_length=200, null=True),
        ),
    ]
