# Generated by Django 3.2.9 on 2022-04-05 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_email', models.CharField(blank=True, max_length=250, null=True)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=250, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=250, null=True)),
                ('zoom_meeting_password', models.CharField(blank=True, max_length=250, null=True)),
                ('zoom_topic', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('start_url', models.CharField(blank=True, max_length=800, null=True)),
                ('join_url', models.CharField(blank=True, max_length=800, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_management.meeting')),
            ],
        ),
    ]
