# Generated by Django 3.2.9 on 2022-04-05 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_title', models.CharField(blank=True, max_length=500, null=True)),
                ('survey_open_date', models.DateTimeField(null=True)),
                ('survey_close_date', models.DateTimeField(null=True)),
                ('survey_description', models.CharField(blank=True, max_length=200000, null=True)),
                ('document', models.CharField(blank=True, max_length=200000, null=True)),
                ('doc_ref', models.CharField(blank=True, default='BECY4V03E0', max_length=200, null=True)),
                ('survey_status', models.CharField(blank=True, default='Draft', max_length=200000)),
                ('permissions', models.ManyToManyField(blank=True, related_name='survey_permissions', to=settings.AUTH_USER_MODEL)),
                ('survey_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, max_length=200, null=True)),
                ('question_title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('documents', models.CharField(blank=True, max_length=200000, null=True)),
                ('doc_ref', models.CharField(blank=True, default='81VTIRRCTU', max_length=200, null=True)),
                ('answer', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyRepondents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_responses', models.ManyToManyField(blank=True, related_name='selected_responses', to='surveys.SurveyResponses')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestions')),
            ],
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='survey_responses', to='surveys.SurveyResponses'),
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
    ]
