# Generated by Django 3.2.9 on 2022-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20220922_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='doc_ref',
            field=models.CharField(blank=True, default='NSZKH3C77O', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='doc_ref',
            field=models.CharField(blank=True, default='G1LOQOLDE6', max_length=200, null=True),
        ),
    ]
