# Generated by Django 3.2.9 on 2022-04-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=20)),
                ('server_id', models.CharField(max_length=100, null=True)),
                ('mac_address', models.CharField(max_length=100, null=True)),
                ('public_n', models.CharField(max_length=1000)),
                ('public_e', models.CharField(max_length=1000)),
                ('signature', models.CharField(blank=True, max_length=2000)),
                ('user_email', models.CharField(blank=True, max_length=250)),
                ('license_type', models.CharField(blank=True, max_length=250)),
                ('license_expiry_period', models.IntegerField(blank=True, null=True)),
                ('number_of_users', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('organization', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseCurrentUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_users', models.IntegerField(blank=True, null=True)),
                ('number_of_active_users', models.IntegerField(blank=True, default=0, null=True)),
                ('license_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licenses.licensebody')),
            ],
        ),
    ]
