# Generated by Django 3.2.9 on 2022-04-05 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.DateTimeField()),
                ('person_responsible', models.ManyToManyField(blank=True, related_name='agenda_responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('meeting_address', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('invitees', models.ManyToManyField(blank=True, related_name='meeting_invitees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('in_meeting_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_management.meeting')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinutesAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('discussion', models.CharField(blank=True, max_length=400, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=400, null=True)),
                ('agenda_actions', models.ManyToManyField(blank=True, related_name='agenda_actions', to='meeting_management.AgendaAction')),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.CharField(blank=True, max_length=400, null=True)),
                ('agenda', models.ManyToManyField(blank=True, related_name='minutes_agenda', to='meeting_management.MinutesAgenda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invitees', models.ManyToManyField(blank=True, related_name='minutes_rsvp', to='meeting_management.Rsvp')),
                ('parent_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_management.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_id', models.CharField(max_length=200)),
                ('xfdf_string', models.TextField(default='')),
                ('doc_ref', models.CharField(max_length=200)),
                ('annoted_by', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_name', models.CharField(max_length=200)),
                ('agenda_description', models.CharField(blank=True, max_length=200, null=True)),
                ('agenda_document', models.CharField(blank=True, max_length=10000, null=True)),
                ('doc_ref', models.CharField(blank=True, default='G3SUQYPDR1', max_length=200, null=True)),
                ('childreen', models.CharField(blank=True, max_length=200, null=True)),
                ('presenters', models.TextField(blank=True, null=True)),
                ('guests', models.TextField(blank=True, null=True)),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meeting_management.agendaitem')),
                ('parent_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_management.meeting')),
                ('permission', models.ManyToManyField(blank=True, related_name='agenda_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
