# Generated by Django 3.2.9 on 2022-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_management', '0010_alter_agendaitem_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='doc_ref',
            field=models.CharField(blank=True, default='CN7WM87H4R', max_length=200, null=True),
        ),
    ]
